# Generated by Django 5.2.5 on 2025-09-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='colors',
        ),
    ]
